server:
  port: 8080
spring:
  application:
    name: sharding-order
  # 以下是分片规则配置
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      # 定义数源
      names: m1
      m1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver‐class‐name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/order_db?useUnicode=true
        username: root
        password: 1
    sharding:
      tables:
        t_order:
          # 指定t_order表的数据分布情况，配置数据节点
          actual‐data‐nodes: m1.t_order_$->{1..2}
          # 指定t_order表主键生成策略为SNOWFLAKE
          key‐generator:
            column: order_id
            type: SNOWFLAKE
          # 指定t_order表的分片策略（包括分片键和分片算法）
          table-strategy:
            inline:
              sharding-column: order_id
              algorithm‐expression: t_order_$->{order_id % 2 + 1}
    props:
      # 打开sql输出日志
      sql:
        show: true
logging:
  level:
    druid:
      sql: debug
    com:
      example: debug