version: '2'
services:
  m1:
    image: mysql:5.7.35
    container_name: m1
    hostname: m1
    privileged: true
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    ports:
      - "3308:3306"
    volumes:
      - "./conf/init/m1.sql:/docker-entrypoint-initdb.d/m1.sql"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --lower_case_table_names=1
    networks:
      - mysql_net
networks:
  mysql_net:
    driver: bridge